version: '3'

services:
  jacenterprise-mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: random
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  jacenterprise-springboot-app:
    build:
      context: ./Backend
      dockerfile: Dockerfile.txt
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/random
    depends_on:
      mysql:
        condition: service_healthy
    command: ["java", "-jar", "app.jar"]

  jacenterprise-react-app:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "25000:6001"
    volumes:
      - .:/Frontend/src/app
      - /Frontend/node_modules
    depends_on:
      - springboot-app